// <auto-generated />
using System;
using GestionCabinetMedical.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionCabinetMedical.Migrations.BdCabinetMedical
{
    [DbContext(typeof(BdCabinetMedicalContext))]
    [Migration("20251224211012_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionCabinetMedical.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("NiveauAcces")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Admin__3214EC0704EF404F");

                    b.ToTable("Admin", (string)null);
                });

            modelBuilder.Entity("GestionCabinetMedical.Models.Consultation", b =>
                {
                    b.Property<int>("NumDetail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NumDetail"));

                    b.Property<DateTime?>("DateConsultation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Diagnostic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DossierMedicalId")
                        .HasColumnType("int");

                    b.HasKey("NumDetail")
                        .HasName("PK__Consulta__D84B7AFE32A8846D");

                    b.HasIndex("DossierMedicalId");

                    b.ToTable("Consultation", (string)null);
                });

            modelBuilder.Entity("GestionCabinetMedical.Models.DossierMedical", b =>
                {
                    b.Property<int>("NumDossier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NumDossier"));

                    b.Property<string>("GroupeSanguin")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("MedecinId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("NumDossier")
                        .HasName("PK__DossierM__4ED7359D35DBAEAC");

                    b.HasIndex("MedecinId");

                    b.HasIndex("PatientId");

                    b.ToTable("DossierMedical", (string)null);
                });

            modelBuilder.Entity("GestionCabinetMedical.Models.Medecin", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Specialite")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Medecin__3214EC07F94A74B8");

                    b.ToTable("Medecin", (string)null);
                });

            modelBuilder.Entity("GestionCabinetMedical.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RendezVousId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Notifica__3214EC079CE1CB28");

                    b.HasIndex("RendezVousId");

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("GestionCabinetMedical.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("NumSecuriteSociale")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Patient__3214EC075743A3DC");

                    b.HasIndex(new[] { "NumSecuriteSociale" }, "UQ__Patient__C8EA55E7FFB228AB")
                        .IsUnique();

                    b.ToTable("Patient", (string)null);
                });

            modelBuilder.Entity("GestionCabinetMedical.Models.PersonnelMedical", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Fonction")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Personne__3214EC079BFE4B2E");

                    b.ToTable("PersonnelMedical", (string)null);
                });

            modelBuilder.Entity("GestionCabinetMedical.Models.RendezVou", b =>
                {
                    b.Property<int>("NumCom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NumCom"));

                    b.Property<DateTime>("DateHeure")
                        .HasColumnType("datetime");

                    b.Property<int>("MedecinId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Statut")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("En attente");

                    b.HasKey("NumCom")
                        .HasName("PK__RendezVo__7DF505B37D375ABF");

                    b.HasIndex("MedecinId");

                    b.HasIndex("PatientId");

                    b.ToTable("RendezVous");
                });

            modelBuilder.Entity("GestionCabinetMedical.Models.RessourceMedicale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Ressourc__3214EC07AC3A39AC");

                    b.ToTable("RessourceMedicale", (string)null);
                });

            modelBuilder.Entity("GestionCabinetMedical.Models.Secretaire", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Service")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Secretai__3214EC07401A3E4D");

                    b.ToTable("Secretaire", (string)null);
                });

            modelBuilder.Entity("GestionCabinetMedical.Models.Traitement", b =>
                {
                    b.Property<int>("NumPro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NumPro"));

                    b.Property<int>("ConsultationId")
                        .HasColumnType("int");

                    b.Property<string>("TypeTraitement")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("NumPro")
                        .HasName("PK__Traiteme__75833A615C2DFE7A");

                    b.HasIndex("ConsultationId");

                    b.ToTable("Traitement", (string)null);
                });

            modelBuilder.Entity("GestionCabinetMedical.Models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("EstActif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Utilisat__3214EC0726F305A9");

                    b.HasIndex(new[] { "Email" }, "UQ__Utilisat__A9D105349A9BE6AA")
                        .IsUnique();

                    b.ToTable("Utilisateur", (string)null);
                });

            modelBuilder.Entity("GestionCabinetMedical.Models.Admin", b =>
                {
                    b.HasOne("GestionCabinetMedical.Models.Utilisateur", "IdNavigation")
                        .WithOne("Admin")
                        .HasForeignKey("GestionCabinetMedical.Models.Admin", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Admin__Id__3B75D760");

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("GestionCabinetMedical.Models.Consultation", b =>
                {
                    b.HasOne("GestionCabinetMedical.Models.DossierMedical", "DossierMedical")
                        .WithMany("Consultations")
                        .HasForeignKey("DossierMedicalId")
                        .IsRequired()
                        .HasConstraintName("FK__Consultat__Dossi__5165187F");

                    b.Navigation("DossierMedical");
                });

            modelBuilder.Entity("GestionCabinetMedical.Models.DossierMedical", b =>
                {
                    b.HasOne("GestionCabinetMedical.Models.Medecin", "Medecin")
                        .WithMany("DossierMedicals")
                        .HasForeignKey("MedecinId")
                        .IsRequired()
                        .HasConstraintName("FK__DossierMe__Medec__4D94879B");

                    b.HasOne("GestionCabinetMedical.Models.Patient", "Patient")
                        .WithMany("DossierMedicals")
                        .HasForeignKey("PatientId")
                        .IsRequired()
                        .HasConstraintName("FK__DossierMe__Patie__4CA06362");

                    b.Navigation("Medecin");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("GestionCabinetMedical.Models.Medecin", b =>
                {
                    b.HasOne("GestionCabinetMedical.Models.Utilisateur", "IdNavigation")
                        .WithOne("Medecin")
                        .HasForeignKey("GestionCabinetMedical.Models.Medecin", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Medecin__Id__3E52440B");

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("GestionCabinetMedical.Models.Notification", b =>
                {
                    b.HasOne("GestionCabinetMedical.Models.RendezVou", "RendezVous")
                        .WithMany("Notifications")
                        .HasForeignKey("RendezVousId")
                        .HasConstraintName("FK__Notificat__Rende__5CD6CB2B");

                    b.Navigation("RendezVous");
                });

            modelBuilder.Entity("GestionCabinetMedical.Models.Patient", b =>
                {
                    b.HasOne("GestionCabinetMedical.Models.Utilisateur", "IdNavigation")
                        .WithOne("Patient")
                        .HasForeignKey("GestionCabinetMedical.Models.Patient", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Patient__Id__4222D4EF");

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("GestionCabinetMedical.Models.RendezVou", b =>
                {
                    b.HasOne("GestionCabinetMedical.Models.Medecin", "Medecin")
                        .WithMany("RendezVous")
                        .HasForeignKey("MedecinId")
                        .IsRequired()
                        .HasConstraintName("FK__RendezVou__Medec__48CFD27E");

                    b.HasOne("GestionCabinetMedical.Models.Patient", "Patient")
                        .WithMany("RendezVous")
                        .HasForeignKey("PatientId")
                        .IsRequired()
                        .HasConstraintName("FK__RendezVou__Patie__49C3F6B7");

                    b.Navigation("Medecin");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("GestionCabinetMedical.Models.Secretaire", b =>
                {
                    b.HasOne("GestionCabinetMedical.Models.Utilisateur", "IdNavigation")
                        .WithOne("Secretaire")
                        .HasForeignKey("GestionCabinetMedical.Models.Secretaire", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Secretaire__Id__44FF419A");

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("GestionCabinetMedical.Models.Traitement", b =>
                {
                    b.HasOne("GestionCabinetMedical.Models.Consultation", "Consultation")
                        .WithMany("Traitements")
                        .HasForeignKey("ConsultationId")
                        .IsRequired()
                        .HasConstraintName("FK__Traitemen__Consu__5441852A");

                    b.Navigation("Consultation");
                });

            modelBuilder.Entity("GestionCabinetMedical.Models.Consultation", b =>
                {
                    b.Navigation("Traitements");
                });

            modelBuilder.Entity("GestionCabinetMedical.Models.DossierMedical", b =>
                {
                    b.Navigation("Consultations");
                });

            modelBuilder.Entity("GestionCabinetMedical.Models.Medecin", b =>
                {
                    b.Navigation("DossierMedicals");

                    b.Navigation("RendezVous");
                });

            modelBuilder.Entity("GestionCabinetMedical.Models.Patient", b =>
                {
                    b.Navigation("DossierMedicals");

                    b.Navigation("RendezVous");
                });

            modelBuilder.Entity("GestionCabinetMedical.Models.RendezVou", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("GestionCabinetMedical.Models.Utilisateur", b =>
                {
                    b.Navigation("Admin");

                    b.Navigation("Medecin");

                    b.Navigation("Patient");

                    b.Navigation("Secretaire");
                });
#pragma warning restore 612, 618
        }
    }
}
